# Generated by Django 3.1.2 on 2020-12-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asyari', '0003_auto_20201206_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='Asyari.Tag'),
        ),
    ]
