# Generated by Django 3.1.2 on 2021-01-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asyari', '0004_auto_20201206_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
