# Generated by Django 3.1.2 on 2021-02-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asyari', '0007_custumer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='no_image.jpg', upload_to=''),
        ),
    ]
